AOSC-Dev/autobuild4

- sets/exports.json
This PR allows RECONF to be overridden by arch. specific requirements.
> sets/exports: allow arch. specific override of RECONF

- .gitignore
- CMakeLists.txt
- lib/default.sh
- native/abnativeelf.cpp
- native/abnativeelf.hpp
- native/abnativefunctions.cpp
- pm/dpkg.sh
- sets/exports.json
This pull request merges a preliminary implementation of Spiral, Debian-compatible dependency marker for AOSC OS. This implementation currently supports marking the following:
- soname support (imprecise, uses a simple rule logic)
- GObject-Introspection typelibs (`gir1.2-*`)
- Python modules (`python{2,3}-*`)
> 4.1: Spiral Support

- arch/optenv32.sh
This PR disables the generation of Spiral related content for optenv targets, since they are not used.
> arch/optenv32: disable Spiral generation

- lib/default-flags.sh
This PR adds additional arguments for Autotools, which specifies the runtime data path to /run, to avoid files to be written to the non-standard path /var/run.
> default-flags: specify runtime data path for autotools

- arch/_common.sh
- arch/amd64.sh
https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html argues that amd64 has enough registers to not be bothered by the FP. Google, Meta, Fedora, Ubuntu, and Arch seem to agree.
Should we follow suit? The main justification is that the FP gives real-time profiling tools a proper view of the stack.
> [RFC] arch/amd64: let the frame pointer return

- arch/_common.sh
- arch/amd64.sh
- arch/ppc64el.sh
- lib/default-defines.sh
- proc/12-arch-flags.sh
- proc/50-build-exec.sh
- proc/51-build-hwcaps.sh
- qa/post/hwcaps.sh
- templates/10-autotools.sh
This PR adds an implementation of packaging helpers to build HWCAPS for subtargets.
The documentation can be read here: https://hackmd.io/@Cyanoxygen/BysSMH-RR
> Core 12: HWCAPS helpers

- arch/i486.sh
- arch/sparc64.sh
-O2 -fno-tree-ch generates better results than -Os when keeping binary size small, especially on architectures with severe penalties for non-aligned load/store, and/or architectures with rather small L2/L3 caches.
Also Glibc might be miscompiled by -Os switch, so I suggest using -O2 instead of -Os on selected packages.
See [https://github.com/openwrt/openwrt/commit/bf604f35035ae49a3db8a1e1ff67f512a0de86bd](url)
-mtune=bonnell is suboptimal for any CPU other than first generation Intel Atom processors, and will increase binary size.
https://github.com/AOSC-Dev/aosc-os-abbs/pull/7406
With this patch GCC should generate very promising results for Intel P6 variants / AMD K7 Athlons .
Fixes a typo in sparc64 too.
> Change default CFLAGS for i486 target

- lib/default-defines.sh
- proc/01-core-defines.sh
- proc/70-scriptlets.sh
dpkg allows maintscripts to be absent. In this case it won't try to run non-existant maintscripts. Add an array and a switch to allow skipping generation some or all of maintscripts.
> Allow packages to skip maintscripts generation

- arch/_common.sh
- arch/amd64.sh
- arch/amd64_avx+.sh
- arch/amd64_avx2+.sh
Apologies for abruptly reverting that change but this change is best queued for Core 12 when we survey potential changes for core toolchains. cc @Artoria2e5  @jiegec 
From original pull request:
> https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html argues that amd64 has enough registers to not be bothered by the FP. Google, Meta, Fedora, Ubuntu, and Arch seem to agree.
>
> Should we follow suit? The main justification is that the FP gives real-time profiling tools a proper view of the stack.
> [Core 12] arch/amd64: let the frame pointer return

- arch/_common_switches.sh
Fortification level 3 is supported sinced glibc 2.34 and GCC 12.
Enable it for better hardening performance.
> arch/_common_switches: bump FORTIFY_SOURCE to 3

- arch/_common_switches.sh
- lib/default-defines.sh
- sets/exports.json
Control-flow proection only functions (via compiler and/or kernel, and hardware) on ...
- amd64 (x86-64): Intel CET (compiler: `-fcf-protection=full`, kernel: `CONFIG_CET`).
- arm64 (AArch64): PAC + BTI (compiler: `-mbranch-protection=standard`, kernel: `CONFIG_ARM64_BTI` + `ARM64_PTR_AUTH`).
> arch: implement control-flow protection via AB_FLAGS_CFP

- arch/loongarch64.sh
Per "Software Development and Build Convention for LoongArch Architectures v0.2":
> Desktop and server operating operating systems both need to support CPU platforms with at least 128-bit vector units.
>
> To support 128-bit vector instructions, the compilation toolchain should use the -march=la64v1.0 compilation option when compiling desktop and server operating systems.
>
> ...
>
> The desktop and server operating system compilation toolchain should enable -mno-strict-align compilation option.
Update default arch/loongarch64 flags to comply with Convention v0.2.
Ref: https://github.com/loongson/la-softdev-convention/blob/v0.2/la-softdev-convention.adoc
> arch/loongarch64: comply with la-softdev-convention v0.2

- arch/_common_switches.sh
Otherwise for every invocation the compiler will emit this warning:
```
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
```
> arch/common-switches: undef `_FORTIFY_SOURCE` before redefining

- templates/10-autotools.sh
For Non-standard configure scripts
before:
```bash
[INFO]: Re-generating Autotools scripts ...
In file included from /usr/bin/autobuild:13
from /usr/lib/autobuild4/proc/50-build-exec.sh:29
from /usr/lib/autobuild4/templates/10-autotools.sh:51 /usr/lib/autobuild4/templates/10-autotools.sh:36: In function `build_autotools_regenerate': /usr/lib/autobuild4/templates/10-autotools.sh:36: error: command exited with 1 35 | else
> 36 | abdie 'Necessary files not found for script regeneration - non-standard Autotools source?'
37 | fi
autobuild encountered an error and couldn't continue. Necessary files not found for script regeneration - non-standard Autotools source?
```
after:
```bash
2: [DEBUG]: Registered filter: retro_drop_docs
2: In file included from …
```
> templates/autotools: fix Non-standard configure script recognition

- arch/loongson3.sh
For Loongson 3 two workarounds for LL/SC may be needed:
1:
sync               # "LLSYNC"
ll	$7,0($4)
bne	$7,$3,2f
li	$2,0
move	$1,$6
sc	$1,0($4)
beq	$1,$0,1b
li	$2,1
2:
sync               # "TGTSYNC"
The message of the AOSC patch adding -mfix-loongson3-llsc to GCC claims "Binutils only handles LLSYNC, not TGTSYNC."  It's no longer correct: the patch was written in 2018, but when the Binutils LL/SC errata workaround was upstreamed in 2019 it actually handles both LLSYNC and TGTSYNC.
As in abbs we already configure Binutils to enable the workaround by default for loongson3, we don't need the GCC workaround anymore.  Drop it here now, and it'll be dropped from our GCC patchset too.
Link: https://github.com/AOSC-Dev/aosc-os-abbs/blob/6e87aebe7f8d/app-devel/binutils/01-main/defines#L35
Link: …
> loongson3: Drop -mfix-loongson3-llsc

- arch/optenv32.sh
- filters/optenv32_drop_shared_files.sh
- Do not create replacement symlinks - handle this in aosc-aaa+32 as it creates directory structures for the base optenv32 environment.
- Do not remove non-prefixed data files as it will be part of the symlinked structure.
> filters/optenv32_drop_shared_files.sh: adjust for aosc-aaa+32

- qa/pre/variables.sh
this reduce chance of confusion when switch package between templates and build file
> qa: add QA error 'build' file exist when ABTYPE is set to non 'self' value

- templates/15-gomod.sh
Tested the following three packages:
- sing-box(no need to manually define GO_PACKAGES and can run `go get` in `$SRCDIR`) now can be built properly.
- [opentofu](https://github.com/AOSC-Dev/aosc-os-abbs/pull/10546)(need to manually define GO_PACKAGES and can run `go get` in `$SRCDIR`) now can be built properly.
- gdu(need to manually define GO_PACKAGES but can not run `go get` in `$SRCDIR`) now can be built properly.
> templates/15-gomod: make go get targets customizable too

- arch/loongarch64_nosimd.sh
- sets/arch_groups.json
- sets/arch_targets.json
Unlike what is specified in "Software Development and Build Convention for LoongArch Architectures v0.2", this port is intended for SIMD-less platforms such as the Loongson 2K0300.
Ref: https://github.com/loongson/la-softdev-convention/blob/v0.2/la-softdev-convention.adoc
> arch: add loongarch64/nosimd target

- templates/15-gomod.sh
Previously when a package uses gomod template multiple times, sub-packages built after the first one would fail because $SRCDIR/abbuild exists.
This patch fixes mkdir errors by adding -p option to mkdir, avoiding re-creation of subdirs and returning errors when $SRCDIR/abbuild has already been created by previous builds.
See [incus build error log](https://buildit.aosc.io/logs/92418-incus-6.14.0-amd64-Ricks-Ryzen-Box-2025-06-28-21:47:30.txt).
> templates/15-gomod.sh: fix mkdir errors

- CMakeLists.txt
- sets/section
Fix #58 which did not add `{contrib,nonfree}/metrics`
> sets/section: new section `{contrib,nonfree}/metrics`

- native/abnativeelf.cpp
Instead of testing non-zero, make sure the flags are equal after testing to avoid ambiguity.
> abnativeelf: test EF_MIPS_* flags against themselves
